version: "3.9"

services:
  frontend:
    build:
      context: ./project
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your_secret_here
      - SERVER_URL=http://server2:5000
    depends_on:
      - server2
      - stream

  server2:
    build:
      context: ./server2
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production

  stream:
    build:
      context: ./stream
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
